<?php
/**
 * Created with PhpStorm at 17.04.16.
 *
 * @author Dominik Müller (Ashura) ashura@aimei.ch
 * @link   http://aimei.ch/developers/Ashura
 */

namespace AppBundle\Entity;


use Doctrine\ORM\Mapping as ORM;

/**
 * Class Thermometer
 *
 * @ORM\Entity()
 *
 * @package AppBundle\Entity
 */
class ThermometerAndHumidityMeter extends Device
{
    /**
     * @return string
     */
    public function getDeviceName()
    {

        return 'Thermometer/Feuchtigkeitsmesser';
    }

    /**
     * @return string
     */
    public function getIcon():string
    {
        return parent::getIcon(); // TODO: Change the autogenerated stub
    }


    public function getInformations():array
    {
        return parent::getInformations(); // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     */
    private function getBaseUrl()
    {
        
        return $this->getIp().'/arduino/';
    }
}
